### PR TITLE
Generate the template ini file.

### PR DESCRIPTION
**Pull request by kdorheim**
This PR merges the materials to create and test a template ini file. The scenario name has been removed from one of the CMIP5 RCP ini files and replaced with the tag TEMPLATE. This PR is also a text to make sure that the github workflows are set up properly.

### CODE REVIEW

**Comment by kdorheim** [comment]
@bpbond I am stumped why the test-coverage is still failing, does it have to do with how the git hub actions sets were set up? do you have time to take a look at it?

**Comment by bpbond** [comment]
Yes will do

**Comment by bpbond** [comment]
There are no tests! So no package coverage can be calculated. I think that's the problem.

**Comment by bpbond** [comment]
Whoops I pushed sample test to `master` by accident, sorry

**Comment by bpbond** [comment]
That wasn't it, although the sample test I added doesn't actually test any code. Maybe just delete the coverage test for now, until you have code to test?

**Comment by kdorheim** [comment]
interesting, okay I will remove the test for now!

**Pull request merged**
